services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=contas'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - 5432:5432  
  app:
    image: estevaofreitas/api-contas:latest
    depends_on:
       - postgres
    ports:
      - 8080:8080
    extra_hosts:
      - "postgres.db:host-gateway"