spring:
    application:
        name: api.contas

    servlet:
        multipart:
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
    
    datasource:
        url: jdbc:postgresql://localhost:5432/contas
        username: user
        password: secret
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate

springdoc:
    api-docs:
        path: /api-docs

