spring:
    application:
        name: api.contas
    
    datasource:
        url: jdbc:postgresql://localhost:5432/contas
        username: user
        password: secret
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate

springdoc:
    api-docs:
        path: /api-docs