spring:
    profiles:
        active: local
    application:
        name: api.contas

    servlet:
        multipart:
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB

security:
    jwt:
        converter:
            resource-id: client-api-contas
            principal-attribute: principal_username

springdoc:
    api-docs:
        path: /api-docs
---
spring:
    config:
        activate:
            on-profile: local
    datasource:
        url: ${DATABASE_CONNECTION_STRING:jdbc:postgresql://localhost:5432/contas} 
        username: user
        password: secret
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_REALM_URL:http://localhost:9090/realms/contas}
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

    docker:
        compose:
            enabled: true
            file: ./build/debug-compose.yaml

---

spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: ${DATABASE_CONNECTION_STRING:jdbc:postgresql://localhost:5432/contas} 
        username: user
        password: secret
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_REALM_URL:http://localhost:9090/realms/contas}
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

    docker:
        compose:
            enabled: true
            file: ./build/debug-compose.yaml

logging:
    level:
        '[org.springframework.security]': DEBUG
