spring:
    application:
        name: api.contas

    servlet:
        multipart:
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
    
    datasource:
        url: jdbc:postgresql://postgres.db:5432/contas
        username: user
        password: secret
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:9090/realms/contas
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

    docker:
        compose:
            enabled: true
            file: ./build/debug-compose.yaml

security:
    jwt:
        converter:
            resource-id: client-api-contas
            principal-attribute: principal_username

logging:
    level:
        '[org.springframework.security]': DEBUG

springdoc:
    api-docs:
        path: /api-docs

