CREATE TABLE IF NOT EXISTS public.contas (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	data_pagamento timestamp(6) NULL,
	data_vencimento timestamp(6) NULL,
	descricao varchar(255) NULL,
	situacao varchar(255) NULL,
	valor numeric(38, 2) NULL,
	CONSTRAINT contas_pkey PRIMARY KEY (id)
);